export const ROUTER_NAMES = {
  MAIN: "main",
  SIGN_IN: "login",
  SIGN_UP: "register",
  SETTINGS: "settings",
  USERS: "users",
  USER_BY_ID: "user-by-id",
  USER_PROFILE: "user-profile",
  USER_SKILLS: "user-skills",
  USER_LANGUAGES: "user-languages",
  USER_CVS: "user-cvs",
  PROJECTS: "projects",
  CVS: "cvs",
  CV_BY_ID: "cv-by-id",
  CVS_DETAILS: "cv-details",
  CVS_SKILLS: "cv-skills",
  CVS_PROJECTS: "cv-projects",
  CVS_PREVIEW: "cv-preview",
  DEPARTMENTS: "departments",
  POSITIONS: "positions",
  SKILLS: "skills",
  LANGUAGES: "languages",
};
