import { type ThemeDefinition } from "vuetify";

// Here we can redefine some Vuetify styles in light theme
export const appLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    // background: "#FFFFFF",
    // error: "#B00020",
    // info: "#2196F3",
    // "on-surface-variant": "#EEEEEE",
    // primary: "#1867C0",
    // "primary-darken-1": "#1F5592",
    // secondary: "#48A9A6",
    // "secondary-darken-1": "#018786",
    // success: "#4CAF50",
    // surface: "#FFFFFF",
    // "surface-bright": "#FFFFFF",
    // "surface-light": "#EEEEEE",
    // "surface-variant": "#424242",
    // warning: "#FB8C00",
  },
  variables: {
    // "activated-opacity": 0.12,
    // "border-color": "#C63031",
    // "border-opacity": 0.12,
    // "disabled-opacity": 0.38,
    // "dragged-opacity": 0.08,
    // "focus-opacity": 0.12,
    // "high-emphasis-opacity": 0.87,
    // "hover-opacity": 0.04,
    // "idle-opacity": 0.04,
    // "medium-emphasis-opacity": 0.6,
    // "pressed-opacity": 0.12,
    // "selected-opacity": 0.08,
    // "theme-code": "#F5F5F5",
    // "theme-kbd": "#212529",
    // "theme-on-code": "#000000",
    // "theme-on-kbd": "#FFFFFF",
  },
};
