import { type ThemeDefinition } from "vuetify";

// Here we can redefine some Vuetify styles in dark theme
export const appDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    // background: "#121212",
    // error: "#CF6679",
    // info: "#2196F3",
    // "on-surface-variant": "#424242",
    // primary: "#2196F3",
    // "primary-darken-1": "#277CC1",
    // secondary: "#54B6B2",
    // "secondary-darken-1": "#48A9A6",
    // success: "#4CAF50",
    // surface: "#212121",
    // "surface-bright": "#ccbfd6",
    // "surface-light": "#424242",
    // "surface-variant": "#a3a3a3",
    // warning: "#FB8C00",
  },
  variables: {
    // "activated-opacity": 0.12,
    // "border-color": "#FFFFFF",
    // "border-opacity": 0.12,
    // "disabled-opacity": 0.5,
    // "dragged-opacity": 0.08,
    // "focus-opacity": 0.12,
    // "high-emphasis-opacity": 1,
    // "hover-opacity": 0.04,
    // "idle-opacity": 0.1,
    // "medium-emphasis-opacity": 0.7,
    // "pressed-opacity": 0.16,
    // "selected-opacity": 0.08,
    // "theme-code": "#343434",
    // "theme-kbd": "#212529",
    // "theme-on-code": "#CCCCCC",
    // "theme-on-kbd": "#FFFFFF",
  },
};
